#!/bin/bash 
wget ftp://ftp.eggheads.org/pub/eggdrop/source/1.6/eggdrop1.6.21.tar.gz
gunzip -c eggdrop1.6.21.tar.gz | tar xopf -
cd eggdrop1.6.21
./configure
make config
make
make install
cd ..
rm -r eggdrop1.6.21 eggdrop1.6.21.tar.gz
cd eggdrop
cd scripts
wget https://github.com/chpasswd/tcl/archive/master.zip
unzip master.zip
cd tcl-master
mv * ..
cd ..
rm -r tcl-master 
rm master.zip
